config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  post 'contacts/create'
  get '/' => 'public/homes#top', as: 'root'
  get 'about' => 'public/homes#about'
  get 'contact' => 'contacts#new'
  get 'privacy' => 'public/homes#privacy'
  get 'terms' => 'public/homes#terms'
  get 'admin' => 'public/homes#admin'
  get 'redirect' => 'public/homes#redirect'
  get 'mypage' => 'public/users#show'
  get 'mypage/edit' => 'public/users#edit'
  get 'mypage/withdraw' => 'public/users#withdraw'
  get 'myprofile' => 'public/users#profile'
  get 'myinfo' => 'public/users#info'

  namespace :master do
    devise_for :admins, controllers: {
      sessions: 'master/admins/sessions',
      registrations: 'master/admins/registrations'
    }
    get '/' => 'admins#top'
    resources :users, only: [:index, :show, :update]
    resources :restaurants, only: [:index, :show]
    resources :tags, only: [:index, :create, :destroy]
  end

  namespace :owner do
    devise_for :restaurants, controllers: {
      sessions: 'owner/restaurants/sessions',
      registrations: 'owner/restaurants/registrations'
    }
    resources :restaurants, only: [:show, :edit, :update] do
      resources :menus
    end
    resources :reservations, only: [:index, :show, :update]
    resources :menu_tags, only: [:create, :destroy]
  end

  namespace :public do
    devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: 'public/users/passwords'
    }
    # get '/' => 'homes#top'
    resources :users, only: [:update] do
      resources :bookmarks, only: [:index, :show]
      get 'reservations/confirm' => 'reservations#confirm'
      get 'reservations/completion' => 'reservations#completion'
      resources :reservations, only: [:index, :show, :new, :create]
    end

    patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'users/withdrawal'
    get 'users/:id/withdrew' => 'users#withdrew', as: 'users/withdrew'

    resources :restaurants, only: [:index, :show]
    resources :menus, only: [:index, :show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/menu.rb
class Menu < ApplicationRecord

  belongs_to :restaurant
  has_many :reservation
  has_many :menu_tag, dependent: :destroy

  enum reservation_method: {'ご予約のみ': 0, 'ご予約可能': 1, 'ご予約不可': 2}

  attachment :menu_image
end

app/controllers/owner/base.rb
class Owner::Base < ApplicationController

  # 管理者がログイン中は登録店舗全て閲覧可能
  before_action :authenticate_owner_restaurant!, unless: :master_admin_signed_in?

  # 閲覧しようとする店舗ページがログイン店舗のものかどうか？
  def current_restaurant?
    unless master_admin_signed_in?
      unless (params[:restaurant_id] || params[:id]) == current_owner_restaurant.id.to_s
        redirect_to owner_restaurant_path(current_owner_restaurant)
      end
    end
  end

  # 閲覧しようとするメニューページがログイン店舗のものかどうか？
  def current_menu?
    unless Menu.find_by(id: params[:id], restaurant_id: current_owner_restaurant.id)
      redirect_to owner_restaurant_menus_path(current_owner_restaurant)
    end
  end

end

app/controllers/owner/menu_tags_controller.rb
class Owner::MenuTagsController < Owner::Base

  def create
    new_menu_tag = MenuTag.new
    menu_id = params[:menu_id]
    restaurant_id = params[:restaurant_id]
    @tag_id = params[:tag_id]
    new_menu_tag.tag_id = @tag_id
    new_menu_tag.menu_id = @@menu_id
    new_menu_tag.save
    redirect_to edit_owner_restaurant_menu_path(restaurant_id, menu_id)
  end

  def destroy
    MenuTag.find(params[:tag_id]).destroy
    redirect_to edit_owner_restaurant_menu_path(params[:restaurant_id], params[:menu_id])
  end

end

app/controllers/owner/menus_controller.rb
class Owner::MenusController < Owner::Base

  before_action :current_restaurant?
  before_action :current_menu?, except: %i[index new]
  before_action :api, only: %i[edit new create update]

  def index
    @current_restaurant = current_owner_restaurant
    @menus = Menu.where(restaurant_id: params[:restaurant_id])
  end

  def show
    @menu = Menu.find(params[:id])
    @menu_tags = MenuTag.where(menu_id: params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @menu = Menu.new
    @menu_tags = MenuTag.where(menu_id: params[:id])
    @tags = Tag.all
  end

  def edit
    @menu = Menu.find(params[:id])
    @menu_tags = MenuTag.where(menu_id: params[:id])
    @tags = Tag.all
  end

  def create
    menu_new = Menu.new(menu_params)
    menu_new.restaurant_id = current_owner_restaurant.id
    if menu_new.save
      # 推奨タグの新規追加
      params[:tag_id].each do |tag, box|
        if box == "1"
          menu_tag = MenuTag.new
          menu_tag.menu_id = menu_new.id
          menu_tag.tag_id = tag.to_i
          menu_tag.save
        end
      end

      # フォームに値があるかどうか？
      unless params[:tag].nil?
        # Tagの新規追加
        params[:tag].each do |tag|
          unless Tag.find_by(name: "#{tag}")
            new_tag = Tag.new
            new_tag.name = "#{tag}"
            new_tag.save
          end
        end

        #MenuTagの新規追加
        params[:tag].each do |tag|
          new_menu_tag = MenuTag.new
          new_menu_tag.menu_id = menu_new.id
          new_menu_tag.tag_id = Tag.find_by(name: "#{tag}").id
          new_menu_tag.save
        end
      end

      redirect_to owner_restaurant_menu_path(current_owner_restaurant, menu_new)
    else
      render :edit
    end
  end

  def update
    restaurant = Restaurant.find(params[:restaurant_id])
    menu = Menu.find(params[:id])
    menu.reservation_method = params[:reservation_method].to_i
    if menu.update(menu_params)
      unless params[:tag_id].nil?
        # 推奨タグの追加・削除
        params[:tag_id].each do |tag, box|
          # チェックマークが入っている時の処理（追加）
          if box == "1"
            if MenuTag.find_by(tag_id: tag.to_i, menu_id: menu.id).nil?
              menu_tag = MenuTag.new
              menu_tag.menu_id = menu.id
              menu_tag.tag_id = tag.to_i
              menu_tag.save
            end
          # チェックマークが入っていない時の処理（削除）
          elsif box == "0"
            remove_menu_tag = MenuTag.find_by(tag_id: tag.to_i, menu_id: menu.id)
            unless remove_menu_tag.nil?
              remove_menu_tag.destroy
            end
          end
        end
      end

      # フォームに値があるかどうか？
      unless params[:tag].nil?
        # Tagの新規追加
        params[:tag].each do |tag|
          unless Tag.find_by(name: "#{tag}")
            new_tag = Tag.new
            new_tag.name = "#{tag}"
            new_tag.save
          end
        end

        #MenuTagの新規追加
        params[:tag].each do |tag|
          unless MenuTag.find_by(menu_id: menu.id, tag_id: Tag.find_by(name: "#{tag}").id)
            new_menu_tag = MenuTag.new
            new_menu_tag.menu_id = menu.id
            new_menu_tag.tag_id = Tag.find_by(name: "#{tag}").id
            new_menu_tag.save
          end
        end
      end
      redirect_to owner_restaurant_menu_path(current_owner_restaurant, menu)
    else
      render :edit
    end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to owner_restaurant_menus_path
  end

  private
  def menu_params
    params.require(:menu).permit(
      :title, :menu_image, :content, :cancel, :regular_price,
      :discount_price, :reservation_method, :is_sale_frag
    )
  end

end

app/controllers/owner/rastaurants/confirmations_controller.rb
# frozen_string_literal: true

class Owner::Rastaurants::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/owner/rastaurants/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Owner::Rastaurants::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/owner/rastaurants/passwords_controller.rb
# frozen_string_literal: true

class Owner::Rastaurants::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/owner/rastaurants/registrations_controller.rb
# frozen_string_literal: true

class Owner::Rastaurants::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/owner/rastaurants/sessions_controller.rb
# frozen_string_literal: true

class Owner::Rastaurants::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/owner/rastaurants/unlocks_controller.rb
# frozen_string_literal: true

class Owner::Rastaurants::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/owner/reservations_controller.rb
class Owner::ReservationsController < Owner::Base

  before_action :current_restaurant?, except: [:index]

  def index
    @reservations = Reservation.all
    @menus = Menu.all
    @users = User.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def update
    reservation = Reservation.find(params[:id])
    redirect_to owner_reservation_path(reservation)
  end

  private
  def reservation_params
    params.require(:reservation).permit(:reservation_status)
  end
end

app/controllers/owner/restaurants/confirmations_controller.rb
# frozen_string_literal: true

class Owner::Restaurants::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/owner/restaurants/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Owner::Restaurants::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/owner/restaurants/passwords_controller.rb
# frozen_string_literal: true

class Owner::Restaurants::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/owner/restaurants/registrations_controller.rb
# frozen_string_literal: true

class Owner::Restaurants::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # アカウント登録後
  def after_sign_up_path_for(resource)
    owner_restaurant_path(resource)
  end

  #アカウント編集後
  def after_update_path_for(resource)
    owner_restaurant_path(resource)
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/owner/restaurants/sessions_controller.rb
# frozen_string_literal: true

class Owner::Restaurants::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    owner_restaurant_path(resource)
  end

  def after_sign_out_path_for(resource)
    new_owner_restaurant_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/helpers/owner/menu_tags_helper.rb
module Owner::MenuTagsHelper
end

app/helpers/owner/menus_helper.rb
module Owner::MenusHelper
end

app/views/owner/menus/._form.html.erb
<div class="menu-form">
  <%= form_with model: [restaurant, menu], url: path, local: true do |f| %>
    <section class="menu-status">
      <div class="menu-form1">
        <h3>メニュー詳細</h3>
        <table>
          <tbody>
            <tr>
              <td><%= f.label :title, value: 'メニュー名' %></td>
              <td><%= f.text_field :title %></td>
            </tr>
            <tr>
              <td><%= f.label :regular_price, value: '正規価格（税抜き）：' %></td>
              <td><%= f.number_field :regular_price %> 円</td>
            </tr>
            <tr>
              <td><%= f.label :discount_price, value: '提供価格（税抜き）：' %></td>
              <td><%= f.number_field :discount_price %> 円</td>
            </tr>
            <tr>
              <td><%= f.label :reservation_method, value: '予約方法' %></td>
              <td><%= f.select :reservation_method, Menu.reservation_methods.keys.map {|method| [method]} %></td>
            </tr>
            <tr>
              <td><%= f.label :is_sale_frag, value: '販売ステータス' %></td>
              <td><%= f.select :is_sale_frag, [['販売中', true], ['販売停止中', false]] %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="menu-form2">
        <h3>メニュー画像</h3>
        <div class="menu-image">
          <%= f.attachment_field :menu_image %>
          <div class="image-preview"></div>
          <h4>タグの追加（任意）</h4>
          <%= text_field_tag :tag_name %>
          <%= button_tag '追加', type: 'button', class: "add-tag-btn" %>
          <div id="tag-list"></div>
          </div>
        </div>
      </div>
    </section>
    <section class="menu-tag-form">
      <h3>タグ詳細</h3>
      <table>
        <tbody>
          <%# 編集画面でのみ表示 %>
          <% if truth %>
            <tr>
              <td><h4>現在のタグ一覧</h4></td>
              <td>
                <% menu_tags.each do |menu_tag| %>
                  <div class="menu-tag">
                    <%= Tag.find(menu_tag.tag_id).name %>
                    <%= link_to 'x', {controller: 'menu_tags', action: 'destroy', tag_id: menu_tag, menu_id: params[:id], restaurant_id: params[:restaurant_id]}, method: :delete %>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
          <tr>
            <td><h4>タグの追加<br>（一つ以上選択推奨）</h4></td>
            <td>
              <% tag_count = 0 %>
              <% tags.each do |tag| %>
                <%# 推奨タグ7個を表示 %>
                <% if tag_count < 7 %>
                  <div class="check-box">
                    <% if menu_tags.exists?(tag_id: tag.id) %>
                      <%= check_box :tag_id, tag.id, checked: true %>
                      <%= label_tag :tag_id, "#{tag.name}"%>
                    <% else %>
                      <%= check_box :tag_id, tag.id %>
                      <%= label_tag :tag_id, "#{tag.name}"%>
                    <% end %>
                  </div>
                  <% tag_count += 1 %>
                <% else %>
                  <% break %>
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </section>

    <section class="menu-form-area">
      <div class="content-form">
        <p><%= f.label :content, value: '内容' %></p>
        <%= f.text_area :content %>
      </div>
      <div class="cancel-form">
        <p><%= f.label :cancel, value: 'キャンセル規定' %></p>
        <%= f.text_area :cancel %>
      </div>
    </section>

    <div class="submit"><%= f.button "#{submit}", onclick: 'submit();', type: 'button', class: 'btn' %></div>
  <% end %>

</div>

app/views/owner/menus/.edit.html.erb
<div class="contents menus-edit">
  <h2 class="menus-edit-h2">メニュー編集</h2>
  <%= render partial: 'form', locals: {
    restaurant: @restaurant,
    menu: @menu,
    tags: @tags,
    menu_tags: @menu_tags,
    path: owner_restaurant_menu_path,
    truth: true, submit: '更新'
    } %>
</div>

app/views/owner/menus/.new.html.erb
<div class="contents menus-new">
  <h2>メニュー追加</h2>
  <%= render partial: 'form',
    locals: {
      restaurant: @restaurant,
      menu: @menu,
      tags: @tags,
      menu_tags: @menu_tags,
      path: owner_restaurant_menus_path,
      truth: false, submit: '作成'
    }
  %>
</div>

app/views/owner/menus/_form.html.erb
<div class="menu-form">
  <%= form_with model: [restaurant, menu], url: path, local: true do |f| %>
    <section class="menu-status">
      <div class="menu-form1">
        <h3>メニュー詳細</h3>
        <table>
          <tbody>
            <tr>
              <td><%= f.label :title, value: 'メニュー名' %></td>
              <td><%= f.text_field :title %></td>
            </tr>
            <tr>
              <td><%= f.label :regular_price, value: '正規価格（税抜き）：' %></td>
              <td><%= f.number_field :regular_price %> 円</td>
            </tr>
            <tr>
              <td><%= f.label :discount_price, value: '提供価格（税抜き）：' %></td>
              <td><%= f.number_field :discount_price %> 円</td>
            </tr>
            <tr>
              <td><%= f.label :reservation_method, value: '予約方法' %></td>
              <td><%= f.select :reservation_method, Menu.reservation_methods.keys.map {|method| [method]} %></td>
            </tr>
            <tr>
              <td><%= f.label :is_sale_frag, value: '販売ステータス' %></td>
              <td><%= f.select :is_sale_frag, [['販売中', true], ['販売停止中', false]] %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="menu-form2">
        <h3>メニュー画像</h3>
        <div class="menu-image">
          <%= f.attachment_field :menu_image %>
          <div class="image-preview"></div>
          <h4>タグの追加（任意）</h4>
          <%= text_field_tag :tag_name %>
          <%= button_tag '追加', type: 'button', class: "add-tag-btn" %>
          <div id="tag-list"></div>
          </div>
        </div>
      </div>
    </section>
    <section class="menu-tag-form">
      <h3>タグ詳細</h3>
      <table>
        <tbody>
          <%# 編集画面でのみ表示 %>
          <% if truth %>
            <tr>
              <td><h4>現在のタグ一覧</h4></td>
              <td>
                <% menu_tags.each do |menu_tag| %>
                  <div class="menu-tag">
                    <%= Tag.find(menu_tag.tag_id).name %>
                    <%= link_to 'x', {controller: 'menu_tags', action: 'destroy', tag_id: menu_tag, menu_id: params[:id], restaurant_id: params[:restaurant_id]}, method: :delete %>
                  </div>
                <% end %>
              </td>
            </tr>
          <% end %>
          <tr>
            <td><h4>タグの追加<br>（一つ以上選択推奨）</h4></td>
            <td>
              <% tag_count = 0 %>
              <% tags.each do |tag| %>
                <%# 推奨タグ7個を表示 %>
                <% if tag_count < 7 %>
                  <div class="check-box">
                    <% if menu_tags.exists?(tag_id: tag.id) %>
                      <%= check_box :tag_id, tag.id, checked: true %>
                      <%= label_tag :tag_id, "#{tag.name}"%>
                    <% else %>
                      <%= check_box :tag_id, tag.id %>
                      <%= label_tag :tag_id, "#{tag.name}"%>
                    <% end %>
                  </div>
                  <% tag_count += 1 %>
                <% else %>
                  <% break %>
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </section>

    <section class="menu-form-area">
      <div class="content-form">
        <p><%= f.label :content, value: '内容' %></p>
        <%= f.text_area :content %>
      </div>
      <div class="cancel-form">
        <p><%= f.label :cancel, value: 'キャンセル規定' %></p>
        <%= f.text_area :cancel %>
      </div>
    </section>

    <div class="submit"><%= f.button "#{submit}", onclick: 'submit();', type: 'button', class: 'btn' %></div>
  <% end %>

</div>

app/views/owner/menus/edit.html.erb
<div class="contents menus-edit">
  <h2 class="menus-edit-h2">メニュー編集</h2>
  <%= render partial: 'form', locals: {
    restaurant: @restaurant,
    menu: @menu,
    tags: @tags,
    menu_tags: @menu_tags,
    path: owner_restaurant_menu_path,
    truth: true, submit: '更新'
    } %>
</div>

app/views/owner/menus/edit.html.slim
contents.menus-edit
  h2.menus-edit-h2 メニュー編集
  == render 'form',
    restaurant: @restaurant,
    menu: @menu,
    tags: @tags,
    menu_tags: @menu_tags,
    path: owner_restaurant_menu_path,
    truth: true, submit: '更新'

app/views/owner/menus/index.html.erb
<div class="contents menus-index">
  <h1>Menus</h1>
  <div class="menus-create"><%= link_to 'メニュー作成', new_owner_restaurant_menu_path(@current_restaurant), class: 'btn' %></div>
  <table>
    <thead>
      <tr>
        <th>メニューID</th>
        <th>イメージ画像</th>
        <th>メニュー名</th>
        <th>予約状況</th>
        <th>販売状況</th>
      </tr>
    </thead>
    <% @menus.each do |menu| %>
      <tbody>
        <tr>
          <td><%= menu.id %></td>
          <td><%= attachment_image_tag menu, :menu_image, style: "height: 70px; width: 100px;", fallbak: "no_image.png" %></td>
          <td><%= link_to "#{menu.title}", owner_restaurant_menu_path(@current_restaurant, menu) %></td>
          <td><%= menu.reservation_method %></td>
          <td>
            <% if menu.is_sale_frag == true %>
              <%= '販売中' %>
            <% else %>
              <%= '停止中' %>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/owner/menus/new.html.slim
.contents.menus-new
  h2 メニュー追加
  == render 'form',
    restaurant: @restaurant,
    menu: @menu,
    tags: @tags,
    menu_tags: @menu_tags,
    path: owner_restaurant_menus_path,
    truth: false, submit: '作成'