config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  post 'contacts/create'
  get '/' => 'public/homes#top', as: 'root'
  get 'about' => 'public/homes#about'
  get 'contact' => 'contacts#new'
  get 'privacy' => 'public/homes#privacy'
  get 'terms' => 'public/homes#terms'
  get 'admin' => 'public/homes#admin'
  get 'redirect' => 'public/homes#redirect'
  get 'mypage' => 'public/users#show'
  get 'mypage/edit' => 'public/users#edit'
  get 'mypage/withdraw' => 'public/users#withdraw'
  get 'myprofile' => 'public/users#profile'
  get 'myinfo' => 'public/users#info'

  namespace :master do
    devise_for :admins, controllers: {
      sessions: 'master/admins/sessions',
      registrations: 'master/admins/registrations'
    }
    get '/' => 'admins#top'
    resources :users, only: [:index, :show, :update]
    resources :restaurants, only: [:index, :show]
    resources :tags, only: [:index, :create, :destroy]
  end

  namespace :owner do
    devise_for :restaurants, controllers: {
      sessions: 'owner/restaurants/sessions',
      registrations: 'owner/restaurants/registrations'
    }
    resources :restaurants, only: [:show, :edit, :update] do
      resources :menus
    end
    resources :reservations, only: [:index, :show, :update]
    resources :menu_tags, only: [:create, :destroy]
  end

  namespace :public do
    devise_for :users, controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations',
      passwords: 'public/users/passwords'
    }
    # get '/' => 'homes#top'
    resources :users, only: [:update] do
      resources :bookmarks, only: [:index, :show]
      get 'reservations/confirm' => 'reservations#confirm'
      get 'reservations/completion' => 'reservations#completion'
      resources :reservations, only: [:index, :show, :new, :create]
    end

    patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'users/withdrawal'
    get 'users/:id/withdrew' => 'users#withdrew', as: 'users/withdrew'

    resources :restaurants, only: [:index, :show]
    resources :menus, only: [:index, :show]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

  validates :email, presence: true, length: {maximum:255},
    format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  validates :message, presence: true

end

app/models/menu.rb
class Menu < ApplicationRecord

  belongs_to :restaurant
  has_many :reservation
  has_many :menu_tag, dependent: :destroy

  enum reservation_method: {'ご予約のみ': 0, 'ご予約可能': 1, 'ご予約不可': 2}

  attachment :menu_image
end

app/models/menu_tag.rb
class MenuTag < ApplicationRecord

  belongs_to :tag
  belongs_to :menu

end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :user
  belongs_to :menu

  enum payment_method: {cash: 0}
  # enum payment_method: {credit: 0, cash: 1, bank: 2}

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservation
  has_many :menu, dependent: :destroy

  attachment :restaurant_image

  include JpPrefecture
  jp_prefecture :prefecture, method_name: :pref

  # バリデーションチェック
  validates :email, presence: true
  validates :name, presence: true
  validates :postal_code, presence: true
  validates :phone_number, presence: true

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_id).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_id = JpPrefecture::Prefecture.find(name: prefecture).code
  end

end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :menu_tag, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reservation

  enum user_status: [:"有効会員", :"退会済み", :"強制退会"]

  attachment :profile_image

  validates :name_family, presence: true
  validates :name_first, presence: true
  validates :name_family_kana, presence: true
  validates :name_first_kana, presence: true
  validates :phone_number, presence: true

  def active_for_authentication?
    super && (self.user_status == "有効会員")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_user_permitted_parameters, if: :devise_controller?

  before_action :configure_user_permitted_parameters, if: :devise_controller?
  # before_action :basic_auth
  # protect_from_forgery with: :exception

  # Basic認証設定
  # def basic_auth
  #   authenticate_or_request_with_http_basic do |username, password|
  #     username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
  #   end
  # end

  # def production?
  #   Rails.env.production?
  # end

  # Google Cloud PlatformのAPIキーをJSON形式で保存（gem'gon'）
  def api
    gon.google_platform_api_key = ENV['GOOGLE_PLATFORM_API_KEY']
  end

  def tracking_id
    gon.google_analytics_tracking_id = ENV['GOOGLE_ANALYTICS_TRACKING_ID']
  end

  protected
  def configure_user_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name_family, :name_first, :name_family_kana, :name_first_kana, :phone_number])
  end

  # def configure_restaurant_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:name_family, :name_first, :name_family_kana, :name_first_kana, :phone_number])
  # end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      flash[:success] = 'お問い合わせを受け付けました。'
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/master/base.rb
class Master::Base < ApplicationController
  before_action :authenticate_master_admin!
end

app/controllers/owner/base.rb
class Owner::Base < ApplicationController

  # 管理者がログイン中は登録店舗全て閲覧可能
  before_action :authenticate_owner_restaurant!, unless: :master_admin_signed_in?

  # 閲覧しようとする店舗ページがログイン店舗のものかどうか？
  def current_restaurant?
    unless master_admin_signed_in?
      unless (params[:restaurant_id] || params[:id]) == current_owner_restaurant.id.to_s
        redirect_to owner_restaurant_path(current_owner_restaurant)
      end
    end
  end

  # 閲覧しようとするメニューページがログイン店舗のものかどうか？
  def current_menu?
    unless Menu.find_by(id: params[:id], restaurant_id: current_owner_restaurant.id)
      redirect_to owner_restaurant_menus_path(current_owner_restaurant)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/master/admins_helper.rb
module Master::AdminsHelper
end

app/helpers/master/masters_helper.rb
module Master::MastersHelper
end

app/helpers/master/tags_helper.rb
module Master::TagsHelper
end

app/helpers/master/users_helper.rb
module Master::UsersHelper
end

app/helpers/owner/menus_helper.rb
module Owner::MenusHelper
end

app/views/layouts/.application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <%= favicon_link_tag('favicon.ico') %>
  <%= favicon_link_tag 'home-icon.png', rel: 'apple-touch-icon', size: '180x180', type: 'image/png' %>
  <%= favicon_link_tag 'home-icon.png', rel: 'android-touch-icon', size: '192x192', type: 'image/png' %>
  <title>Matchi</title>
  <script src="//maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_PLATFORM_API_KEY'] %>"></script>
  <%= include_gon %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', "<%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] %>");
  </script>
</head>

<body>
<header>
  <div class="header-container">
    <%# PC画面ヘッダー %>
    <div class="flex pc-header">
      <%= link_to root_path do %>
        <div class="logo-image"></div>
      <% end %>
      <div class="header-nav">
        <nav>
          <ul class="flex header-ul">
            <% url = request.fullpath %>
            <%# urlに'owner'があれば店舗用ヘッダー %>
            <% if url.include?('owner') %>
              <% if master_admin_signed_in? %>
                <li><%= link_to '管理者トップ', new_master_admin_session_path %></li>
                <li><%= link_to '管理者ログアウト', destroy_master_admin_session_path, method: :delete %></li>
              <% end %>
              <% if owner_restaurant_signed_in? %>
                <li><%= link_to '店舗トップ', owner_restaurant_path(current_owner_restaurant) %></li>
                <li><%= link_to '店舗ログアウト', destroy_owner_restaurant_session_path, method: :delete %></li>
              <% end %>
              <% if public_user_signed_in? %>
                <li><%= link_to '一般会員TOP', mypage_path(current_public_user) %></li>
                <li><%= link_to '一般会員ログアウト', destroy_public_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to '一般会員ログイン', new_public_user_session_path %></li>
              <% end %>

            <%# urlに'master'があれば管理者用ヘッダー %>
            <% elsif url.include?('master') %>
              <% if master_admin_signed_in? %>
                <li><%= link_to '店舗新規登録', new_owner_restaurant_registration_path %></li>
                <li><%= link_to '管理者トップ', new_master_admin_session_path %></li>
                <li><%= link_to '管理者ログアウト', destroy_master_admin_session_path, method: :delete %></li>
              <% end %>
              <% if public_user_signed_in? %>
                <li><%= link_to '一般会員TOP', mypage_path(current_public_user) %></li>
                <li><%= link_to '一般会員ログアウト', destroy_public_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to '一般会員ログイン', new_public_user_session_path %></li>
              <% end %>
              <% if owner_restaurant_signed_in? %>
                <li><%= link_to '店舗トップ', owner_restaurant_path(current_owner_restaurant) %></li>
                <li><%= link_to '店舗ログアウト', destroy_owner_restaurant_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to '店舗ログイン', new_owner_restaurant_session_path %></li>
              <% end %>

            <%# 上記以外なら一般ユーザー用ヘッダー %>
            <% else %>
              <% if master_admin_signed_in? && owner_restaurant_signed_in? %>
                <li><%= link_to '管理者トップ', new_master_admin_session_path %></li>
                <li><%= link_to '管理者ログアウト', destroy_master_admin_session_path, method: :delete %></li>
                <li><%= link_to '店舗TOP', owner_restaurant_path(current_owner_restaurant) %></li>
                <li><%= link_to '店舗ログアウト', destroy_owner_restaurant_session_path, method: :delete %></li>
              <% elsif owner_restaurant_signed_in? %>
                <li><%= link_to '店舗TOP', owner_restaurant_path(current_owner_restaurant) %></li>
                <li><%= link_to '店舗ログアウト', destroy_owner_restaurant_session_path, method: :delete %></li>
              <% elsif master_admin_signed_in? %>
                <li><%= link_to '管理者トップ', new_master_admin_session_path %></li>
                <li><%= link_to '管理者ログアウト', destroy_master_admin_session_path, method: :delete %></li>
                <li><%= link_to '店舗ログイン', new_owner_restaurant_session_path %></li>
              <% end %>
              <% if public_user_signed_in? %>
                <li><%= link_to 'MyPage', mypage_path(current_public_user) %></li>
                  <%# if alert.count >= 1 %>
                    <li><%#= link_to 'お知らせがあります。' %></li>
                  <%# end %>
                <li><%= link_to 'ログアウト', destroy_public_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to '新規登録', new_public_user_registration_path %></li>
                <li><%= link_to 'ログイン', new_public_user_session_path %></li>
              <% end %>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>

    <%# スマホ画面ヘッダー %>
    <div class="flex sp-header">
      <div class="hamburger">
        <span class="bar bar-top"></span>
        <span class="bar bar-center"></span>
        <span class="bar bar-bottom"></span>
      </div>
    <%= link_to root_path do %>
      <div class="logo-image"></div>
    <% end %>
      <%# 未読のお知らせの通知 %>
      <div class="alert">
        <i id="alert-bell" class="fa-2x far fa-bell"><div class="hidden icon"></div></i>
      </div>
      <%# ハンバーガーメーニュー %>
      <div class="hamburger-menu">
        <ul>
          <% if public_user_signed_in? %>
            <li><%= link_to 'MyPage', mypage_path(current_public_user) %></li>
          <% else %>
            <li><%= link_to '新規登録', new_public_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_public_user_session_path %></li>
          <% end %>
          <li><%= link_to 'サービス紹介', about_path %></li>
          <li><%= link_to 'レストラン一覧', public_restaurants_path %></li>
          <li><%= link_to 'メニュー一覧', public_menus_path %></li>
          <% if public_user_signed_in? %>
            <li><%= link_to 'ログアウト', destroy_public_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

<main>
  <div class="body-container">
    <%= yield %>
  </div>
</main>

<footer>
  <div class="flex footer-container">
  <%= link_to root_path do %>
    <div class="logo-image"></div>
  <% end %>
    <div class="footer-menu">
      <ul class="footer-links">
        <li><%= link_to 'お問い合わせ', contacts_new_path %></li>
        <li><%= link_to '利用規約', terms_path %></li>
        <li><%= link_to 'プライバシーポリシー', privacy_path %></li>
        <li><%= link_to '運営者情報', admin_path %></li>
      </ul>
    </div>
  </div>
  <div class="copyright">
    <small>©︎ 2020 MasaoSasaki</small>
  </div>
  <div id="move-head">
    <div class="circle move-head"><i class="fa-2x fas fa-arrow-up"></i></div>
  </div>
</body>
</footer>
</html>

app/views/layouts/_error_messages.html.slim
- if model.errors.any?
  .validation-errors
    ul.error-messages
      - model.errors.full_messages.each do |message|
        li.error-message
          = message

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <%= favicon_link_tag('favicon.ico') %>
  <%= favicon_link_tag 'home-icon.png', rel: 'apple-touch-icon', size: '180x180', type: 'image/png' %>
  <%= favicon_link_tag 'home-icon.png', rel: 'android-touch-icon', size: '192x192', type: 'image/png' %>
  <title>Matchi</title>
  <script src="//maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_PLATFORM_API_KEY'] %>"></script>
  <%= include_gon %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', "<%= ENV['GOOGLE_ANALYTICS_TRACKING_ID'] %>");
  </script>
</head>

<body>
<header>
  <div class="header-container">
    <%# PC画面ヘッダー %>
    <div class="flex pc-header">
      <%= link_to root_path do %>
        <div class="logo-image"></div>
      <% end %>
      <div class="header-nav">
        <nav>
          <ul class="flex header-ul">
            <% url = request.fullpath %>
            <%# urlに'owner'があれば店舗用ヘッダー %>
            <% if url.include?('owner') %>
              <% if master_admin_signed_in? %>
                <li><%= link_to '管理者トップ', new_master_admin_session_path %></li>
                <li><%= link_to '管理者ログアウト', destroy_master_admin_session_path, method: :delete %></li>
              <% end %>
              <% if owner_restaurant_signed_in? %>
                <li><%= link_to '店舗トップ', owner_restaurant_path(current_owner_restaurant) %></li>
                <li><%= link_to '店舗ログアウト', destroy_owner_restaurant_session_path, method: :delete %></li>
              <% end %>
              <% if public_user_signed_in? %>
                <li><%= link_to '一般会員TOP', mypage_path(current_public_user) %></li>
                <li><%= link_to '一般会員ログアウト', destroy_public_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to '一般会員ログイン', new_public_user_session_path %></li>
              <% end %>

            <%# urlに'master'があれば管理者用ヘッダー %>
            <% elsif url.include?('master') %>
              <% if master_admin_signed_in? %>
                <li><%= link_to '店舗新規登録', new_owner_restaurant_registration_path %></li>
                <li><%= link_to '管理者トップ', new_master_admin_session_path %></li>
                <li><%= link_to '管理者ログアウト', destroy_master_admin_session_path, method: :delete %></li>
              <% end %>
              <% if public_user_signed_in? %>
                <li><%= link_to '一般会員TOP', mypage_path(current_public_user) %></li>
                <li><%= link_to '一般会員ログアウト', destroy_public_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to '一般会員ログイン', new_public_user_session_path %></li>
              <% end %>
              <% if owner_restaurant_signed_in? %>
                <li><%= link_to '店舗トップ', owner_restaurant_path(current_owner_restaurant) %></li>
                <li><%= link_to '店舗ログアウト', destroy_owner_restaurant_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to '店舗ログイン', new_owner_restaurant_session_path %></li>
              <% end %>

            <%# 上記以外なら一般ユーザー用ヘッダー %>
            <% else %>
              <% if master_admin_signed_in? && owner_restaurant_signed_in? %>
                <li><%= link_to '管理者トップ', new_master_admin_session_path %></li>
                <li><%= link_to '管理者ログアウト', destroy_master_admin_session_path, method: :delete %></li>
                <li><%= link_to '店舗TOP', owner_restaurant_path(current_owner_restaurant) %></li>
                <li><%= link_to '店舗ログアウト', destroy_owner_restaurant_session_path, method: :delete %></li>
              <% elsif owner_restaurant_signed_in? %>
                <li><%= link_to '店舗TOP', owner_restaurant_path(current_owner_restaurant) %></li>
                <li><%= link_to '店舗ログアウト', destroy_owner_restaurant_session_path, method: :delete %></li>
              <% elsif master_admin_signed_in? %>
                <li><%= link_to '管理者トップ', new_master_admin_session_path %></li>
                <li><%= link_to '管理者ログアウト', destroy_master_admin_session_path, method: :delete %></li>
                <li><%= link_to '店舗ログイン', new_owner_restaurant_session_path %></li>
              <% end %>
              <% if public_user_signed_in? %>
                <li><%= link_to 'MyPage', mypage_path(current_public_user) %></li>
                  <%# if alert.count >= 1 %>
                    <li><%#= link_to 'お知らせがあります。' %></li>
                  <%# end %>
                <li><%= link_to 'ログアウト', destroy_public_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to '新規登録', new_public_user_registration_path %></li>
                <li><%= link_to 'ログイン', new_public_user_session_path %></li>
              <% end %>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>

    <%# スマホ画面ヘッダー %>
    <div class="flex sp-header">
      <div class="hamburger">
        <span class="bar bar-top"></span>
        <span class="bar bar-center"></span>
        <span class="bar bar-bottom"></span>
      </div>
    <%= link_to root_path do %>
      <div class="logo-image"></div>
    <% end %>
      <%# 未読のお知らせの通知 %>
      <div class="alert">
        <i id="alert-bell" class="fa-2x far fa-bell"><div class="hidden icon"></div></i>
      </div>
      <%# ハンバーガーメーニュー %>
      <div class="hamburger-menu">
        <ul>
          <% if public_user_signed_in? %>
            <li><%= link_to 'MyPage', mypage_path(current_public_user) %></li>
          <% else %>
            <li><%= link_to '新規登録', new_public_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_public_user_session_path %></li>
          <% end %>
          <li><%= link_to 'サービス紹介', about_path %></li>
          <li><%= link_to 'レストラン一覧', public_restaurants_path %></li>
          <li><%= link_to 'メニュー一覧', public_menus_path %></li>
          <% if public_user_signed_in? %>
            <li><%= link_to 'ログアウト', destroy_public_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

<main>
  <div class="body-container">
    <%= yield %>
  </div>
</main>

<footer>
  <div class="flex footer-container">
  <%= link_to root_path do %>
    <div class="logo-image"></div>
  <% end %>
    <div class="footer-menu">
      <ul class="footer-links">
        <li><%= link_to 'お問い合わせ', contacts_new_path %></li>
        <li><%= link_to '利用規約', terms_path %></li>
        <li><%= link_to 'プライバシーポリシー', privacy_path %></li>
        <li><%= link_to '運営者情報', admin_path %></li>
      </ul>
    </div>
  </div>
  <div class="copyright">
    <small>©︎ 2020 MasaoSasaki</small>
  </div>
  <div id="move-head">
    <div class="circle move-head"><i class="fa-2x fas fa-arrow-up"></i></div>
  </div>
</body>
</footer>
</html>

app/views/master/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%# link_to "管理者新規登録", new_master_admin_registration_path %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>